version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    networks:
      - RIA2

networks:
  RIA2:
      name: RIA2